# Generated by Django 5.1.6 on 2025-03-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha_vencimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
