# Generated by Django 5.1.6 on 2025-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
