# Generated by Django 5.1.6 on 2025-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.etiqueta'),
        ),
    ]
